version: "3"
services:
  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafkac
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafkac
      - KAFKA_ADVERTISED_PORT:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - PLAINTEXT_HOST://localhost:80
      - KAFKA_ADVERTISED_LISTENERS:PLAINTEXT://kafkac:9092,PLAINTEXT_HOST://localhost:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP:PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME:PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR:1
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE:true
      - KAFKA_LISTENERS:PLAINTEXT://:9092,PLAINTEXT_HOST://0.0.0.0:80
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - chatappcontainer1
      - chatappcontainer2
    ports:
      - 80:80
      - 9092-9092
  chatappcontainer1:
    build:
      context: .
      args:
        NODE_ENV: production
    environment:
      - PORT=5001
      - KAFKA_ADVERTISED_HOST_NAME=kafkac:9092
      - KAFKA_ADVERTISED_PORT:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_INTER_BROKER_LISTENER_NAME:PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR:2
    depends_on:
      - zookeeper
      - kafka
    command: npm run dev
    volumes:
      - ./:/usr/src/app
  chatappcontainer2:
    build:
      context: .
      args:
        NODE_ENV: production
    environment:
      - PORT=5002
      - KAFKA_ADVERTISED_HOST_NAME=kafkac:9092
      - KAFKA_ADVERTISED_PORT:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_INTER_BROKER_LISTENER_NAME:PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR:2
    depends_on:
      - zookeeper
      - kafka
    command: npm run dev
    volumes:
      - ./:/usr/src/app
