version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
  chatappcontainer1:
    build:
      context: .
      args:
        NODE_ENV: production
    environment:
      - PORT=5001
    command: npm run dev
    volumes:
      - ./:/usr/src/app
  chatappcontainer2:
    build:
      context: .
      args:
        NODE_ENV: production
    environment:
      - PORT=5002
    command: npm run dev
    volumes:
      - ./:/usr/src/app
